name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Create Sum
        run: |
          shasum -a 256 ./gvm > gvm.sum
      - name: Create Release Tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            gvm
            gvm.sum
      - name: Create Latest Tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            LICENSE
            gvm
            gvm.sum